name: Build On Simulator

on:
  push:
    branches:
      -
        release/simulator

jobs:
  build:
    runs-on: macos-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v1
      -
        name: "Select Xcode version"
        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      -
        name: "Show Xcode version"
        run: xcodebuild -version
      -
        name: "Build"
        run: xcodebuild -sdk iphonesimulator -configuration Realase build
