name: "Deploy To Deploygate"

on:
  push:
    branches:
      -
        release/deploygate

jobs:
  build:
    runs-on: macos-latest
    env:
      PROJECT_NAME: 'HelloGithubActions'
      KEYCHAIN: '/Library/Keychains/System.keychain'
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v1
      -
        name: "Select Xcode version"
        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      -
        name: "Show Xcode version"
        run: xcodebuild -version
      -
        name: "Install certificate"
        run: |
          echo "${{ secrets.CERTIFICATE_BASE64 }}" > distribution.cer.txt
          base64 --decode distribution.cer.txt > distribution.cer
          sudo security import distribution.cer -k $KEYCHAIN -T /usr/bin/codesign
      -
        name: "Install secret"
        run: |
          echo "${{ secrets.P12_BASE64 }}" > ios_distribution.p12.txt
          base64 --decode ios_distribution.p12.txt > ios_distribution.p12
          sudo security import ios_distribution.p12 -k $KEYCHAIN -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
      -
        name: "Make Provisiong directory"
        run: mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
      -
        name: "Install provisioning"
        run: |
          echo "${{ secrets.PROVISIONING_BASE64 }}" > distribution.mobileprovision.txt
          base64 --decode distribution.mobileprovision.txt > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision
      -
        name: "Expantion signing config"
        run: |
          echo "${{ secrets.SIGNING_XCCONFIG_BASE64 }}" > Release_xcconfig_base64.txt
          mkdir ./xcconfigs
          base64 --decode Release_xcconfig_base64.txt > xcconfigs/Release_Singing.xcconfig
      -
        name: "Expantion exportOptions"
        run: |
          echo "${{ secrets.EXPORTOPTIONS_BASE64 }}" > exportOptions_base64.txt
          base64 --decode exportOptions_base64.txt > ./exportOptions.plist
      -
        name: "Update cocoapod"
        run: |
          sudo gem update cocoapods
      -
        name: "Pod install"
        run: |
          pod repo update
          pod install
      -
        name: "Build | xcodebuild archive"
        run: >
          set -o pipefail &&
          xcodebuild
            -workspace ${PROJECT_NAME}.xcworkspace
            -sdk iphoneos
            -scheme ${PROJECT_NAME}
            -configuration Release
            -archivePath ./archive
            archive | xcpretty
      -
        name: "Export | xcodebuild export"
        run: >
          set -o pipefail &&
          xcodebuild
            -exportArchive
            -archivePath ./archive.xcarchive
            -exportPath ./build
            -exportOptionsPlist ./exportOptions.plist | xcpretty
      -
        name: "Deploy to deploygate"
        run: >
          curl https://deploygate.com/api/users/addli/apps
            -F file="@./build/Apps/${PROJECT_NAME}.ipa"
            -F token="${{ secrets.DEPLOYGATE_API_KEY }}"
            -F message="Test"
            -F release_note="Test"
      -
        name: "list files"
        run: ls -l
